import { jsPDF } from 'jspdf';
import { CLASS_NAMES, SEVERITY_LABELS, APP_NAME, APP_VERSION } from '../utils/constants';

/**
 * Generate a clinical PDF report for a scan result.
 * Two-page structure: Page 1 = plain language summary, Page 2 = technical detail.
 * Runs entirely in browser via jsPDF.
 */
export async function generateReport({ scan, patient, heatmapBase64, originalImageBase64 }) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  const now = new Date().toLocaleString();

  // ── Page 1: Plain Language Summary ──────────────────────
  // Header bar
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setFillColor(0, 240, 255);
  doc.rect(0, 38, pageWidth, 2, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(0, 240, 255);
  doc.text(`${APP_NAME} Diagnostic Report`, margin, 25);

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 170);
  doc.text(`Generated: ${now}  |  v${APP_VERSION}`, margin, 33);

  let y = 52;

  // Patient info
  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 32, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('PATIENT INFORMATION', margin + 6, y + 8);

  doc.setFontSize(11);
  doc.setTextColor(232, 232, 240);
  doc.text(`Name: ${patient?.name || 'Not specified'}`, margin + 6, y + 16);
  doc.text(`Age: ${patient?.age || 'N/A'}  |  Gender: ${patient?.gender || 'N/A'}`, margin + 6, y + 23);
  doc.text(`Contact: ${patient?.contact || 'N/A'}`, margin + 100, y + 16);

  y += 40;

  // Diagnosis box
  const severityGrade = scan.severity_grade || 0;
  const colors = [
    [0, 255, 136], [0, 240, 255], [255, 184, 0], [255, 0, 110], [255, 51, 85]
  ];
  const diagColor = colors[severityGrade] || colors[0];

  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 45, 3, 3, 'F');

  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('DIAGNOSIS', margin + 6, y + 8);

  doc.setFontSize(18);
  doc.setTextColor(...diagColor);
  doc.text(scan.diagnosis || 'Pending', margin + 6, y + 22);

  doc.setFontSize(11);
  doc.setTextColor(232, 232, 240);
  doc.text(SEVERITY_LABELS[severityGrade] || 'Unknown', margin + 6, y + 32);

  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text(`Confidence: ${((scan.confidence || 0) * 100).toFixed(1)}%`, margin + 6, y + 40);
  doc.text(`Triage: ${scan.triage || 'Pending'}`, margin + 80, y + 40);

  y += 54;

  // What this means (plain language)
  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 40, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('WHAT THIS MEANS', margin + 6, y + 8);

  doc.setFontSize(10);
  doc.setTextColor(232, 232, 240);
  const plainText = getPlainLanguage(severityGrade);
  const lines = doc.splitTextToSize(plainText, contentWidth - 12);
  doc.text(lines, margin + 6, y + 16);

  y += 48;

  // Recommended action
  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 24, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('RECOMMENDED ACTION', margin + 6, y + 8);
  doc.setTextColor(...diagColor);
  doc.text(getTriageAction(scan.triage), margin + 6, y + 18);

  y += 32;

  // Original Image
  if (originalImageBase64) {
    doc.setFontSize(10);
    doc.setTextColor(136, 136, 170);
    doc.text('ORIGINAL SCAN', margin, y + 6);
    try {
      const imgType = originalImageBase64.includes('image/png') ? 'PNG' : 'JPEG';
      const imgData = originalImageBase64.startsWith('data:') ? originalImageBase64 : `data:image/jpeg;base64,${originalImageBase64}`;
      doc.addImage(imgData, imgType, margin, y + 10, 60, 60);
    } catch (e) {
      // Skip on error
    }
  }

  // Heatmap image if available
  if (heatmapBase64) {
    doc.setFontSize(10);
    doc.setTextColor(136, 136, 170);
    doc.text('GRAD-CAM ACTIVATION MAP', margin + 80, y + 6);
    try {
      const type = heatmapBase64.includes('image/jpeg') ? 'JPEG' : 'PNG';
      const data = heatmapBase64.startsWith('data:') ? heatmapBase64 : `data:image/png;base64,${heatmapBase64}`;
      doc.addImage(data, type, margin + 80, y + 10, 60, 60);
    } catch (e) {
      // Skip if image fails
    }
  }

  // Disclaimer at bottom
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 120);
  const disclaimer = 'DISCLAIMER: This report is generated by an AI diagnostic assistance tool and is NOT a substitute for professional medical diagnosis. Results must be reviewed and confirmed by a qualified ophthalmologist. Do not make treatment decisions based solely on this report.';
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth);
  doc.text(disclaimerLines, margin, 275);

  // ── Page 2: Technical Detail ────────────────────────────
  doc.addPage();

  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setFillColor(0, 240, 255);
  doc.rect(0, 28, pageWidth, 2, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(0, 240, 255);
  doc.text('Technical Analysis Detail', margin, 20);

  y = 40;

  // Model info
  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 40, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('MODEL INFORMATION', margin + 6, y + 8);

  doc.setFontSize(9);
  doc.setTextColor(232, 232, 240);
  doc.text(`Model: ${scan.model_used || 'N/A'}`, margin + 6, y + 16);
  doc.text(`MC Dropout Passes: ${scan.mc_passes || 'N/A'}`, margin + 6, y + 23);
  doc.text(`Epistemic Uncertainty: ${scan.uncertainty >= 0 ? scan.uncertainty.toFixed(4) : 'N/A'}`, margin + 6, y + 30);
  doc.text(`Quality Weight: ${scan.quality_score?.toFixed(3) || 'N/A'}`, margin + 6, y + 37);

  y += 48;

  // Class probabilities
  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 50, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('CLASS PROBABILITIES', margin + 6, y + 8);

  const probs = scan.probabilities || [];
  for (let i = 0; i < CLASS_NAMES.length; i++) {
    const prob = probs[i] || 0;
    const barY = y + 14 + i * 7;
    doc.setFontSize(8);
    doc.setTextColor(232, 232, 240);
    doc.text(CLASS_NAMES[i], margin + 6, barY + 3);

    // Draw bar
    doc.setFillColor(30, 30, 50);
    doc.rect(margin + 50, barY, 80, 4, 'F');
    doc.setFillColor(...diagColor);
    doc.rect(margin + 50, barY, 80 * prob, 4, 'F');

    doc.text(`${(prob * 100).toFixed(1)}%`, margin + 135, barY + 3);
  }

  y += 58;

  // Metadata
  doc.setFillColor(15, 15, 30);
  doc.roundedRect(margin, y, contentWidth, 30, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 170);
  doc.text('SCAN METADATA', margin + 6, y + 8);

  doc.setFontSize(9);
  doc.setTextColor(232, 232, 240);
  doc.text(`Scan ID: ${scan.id || 'N/A'}`, margin + 6, y + 16);
  doc.text(`Operator: ${scan.operator_id || 'N/A'}`, margin + 6, y + 23);
  doc.text(`Date: ${scan.created_at ? new Date(scan.created_at).toLocaleString() : now}`, margin + 90, y + 16);
  doc.text(`Offline: ${scan.is_offline ? 'Yes' : 'No'}`, margin + 90, y + 23);

  // Disclaimer
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 120);
  doc.text(disclaimerLines, margin, 275);

  // Save
  const filename = `EyeScan_Report_${patient?.name?.replace(/\s+/g, '_') || 'Patient'}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}

function getPlainLanguage(grade) {
  const texts = [
    'No signs of diabetic retinopathy were detected in this scan. The retina appears healthy. Continue regular annual eye exams to monitor for any changes.',
    'Mild signs of diabetic retinopathy were detected. Small areas of swelling (microaneurysms) may be present. This is an early stage and may not require immediate treatment, but should be monitored regularly.',
    'Moderate signs of diabetic retinopathy were detected. Blood vessels in the retina show some changes. A follow-up with an eye specialist is recommended to determine if treatment is needed.',
    'Severe signs of diabetic retinopathy were detected. Significant changes in the retinal blood vessels were found. Prompt referral to an ophthalmologist is strongly recommended.',
    'Advanced proliferative diabetic retinopathy was detected. New abnormal blood vessels are growing, which can lead to serious vision problems. Immediate specialist referral is critical.',
  ];
  return texts[grade] || texts[0];
}

function getTriageAction(triage) {
  const actions = {
    Routine: 'Continue annual screening. No immediate action required.',
    Priority: 'Schedule a follow-up examination within 1 month.',
    Urgent: 'Refer to ophthalmologist within 1 week.',
    Emergency: 'IMMEDIATE referral to ophthalmology department within 24 hours.',
  };
  return actions[triage] || actions.Routine;
}
