import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useScanResult, useAuth } from '../App';
import { generateReport } from '../services/reportGenerator';
import { showSuccess, showError } from '../services/toastService';
import { FileText, Share2, Download, ArrowLeft, AlertTriangle } from 'lucide-react';

export default function ReportPage() {
  const navigate = useNavigate();
  const { operator } = useAuth();
  const { scanResult } = useScanResult();

  if (!scanResult) {
    return (
      <div className="fade-in">
        <div className="empty-state" style={{ marginTop: 80 }}>
          <AlertTriangle size={48} />
          <h3 className="empty-state-title">No scan data available</h3>
          <p className="empty-state-text">Complete a scan first to generate a report.</p>
          <button className="btn btn-primary mt-24" onClick={() => navigate('/scan')}>Start Scan</button>
        </div>
      </div>
    );
  }

  async function handleGeneratePDF() {
    try {
      const filename = await generateReport({
        scan: {
          ...scanResult,
          operator_id: operator.id,
          quality_score: scanResult.quality?.qualityWeight,
        },
        patient: scanResult.patient || { name: 'Not specified' },
        heatmapBase64: scanResult.heatmap_base64,
        originalImageBase64: scanResult.thumbnail,
      });
      showSuccess(`Report saved: ${filename}`);
    } catch (err) {
      showError('Failed to generate report: ' + err.message);
    }
  }
  function shareWhatsApp() {
    const text = [
      `🔬 Eye Scan Diagnostic Report`,
      `Diagnosis: ${scanResult.diagnosis}`,
      `Severity: Grade ${scanResult.severity_grade}/4`,
      `Confidence: ${(scanResult.confidence * 100).toFixed(1)}%`,
      `Triage: ${scanResult.triage}`,
      `\nGenerated by Eye Scan Ophthalmic Diagnostic System`,
    ].join('\n');
    
    if (navigator.share) {
      navigator.share({ title: 'Eye Scan Report', text: text }).catch(console.error);
    } else {
      window.location.href = `https://wa.me/?text=${encodeURIComponent(text)}`;
    }
  }

  return (
    <div className="fade-in">
      <div className="page-header flex items-center gap-16">
        <button className="btn btn-ghost" onClick={() => navigate(-1)}><ArrowLeft size={20} /></button>
        <div>
          <h1 className="page-title">Generate Report</h1>
          <p className="page-subtitle">Create and share clinical report</p>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 24 }}>
        {/* Report preview */}
        <div className="glass-card">
          <h3 style={{ fontSize: 14, fontWeight: 700, marginBottom: 16, color: 'var(--text-secondary)' }}>REPORT PREVIEW</h3>
          <div style={{ background: 'var(--bg-card)', borderRadius: 12, padding: 20, border: '1px solid var(--border-subtle)' }}>
            <div style={{ borderBottom: '2px solid var(--cyan)', paddingBottom: 12, marginBottom: 16 }}>
              <h4 className="font-heading text-cyan" style={{ fontSize: 16 }}>Eye Scan Diagnostic Report</h4>
              <p className="text-xs text-dim">{new Date().toLocaleString()}</p>
            </div>

            <div style={{ marginBottom: 16 }}>
              <p className="text-xs text-dim">DIAGNOSIS</p>
              <p style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)' }}>{scanResult.diagnosis}</p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
              <div>
                <p className="text-xs text-dim">Severity</p>
                <p className="font-mono">Grade {scanResult.severity_grade}/4</p>
              </div>
              <div>
                <p className="text-xs text-dim">Confidence</p>
                <p className="font-mono">{(scanResult.confidence * 100).toFixed(1)}%</p>
              </div>
              <div>
                <p className="text-xs text-dim">Triage</p>
                <p className="font-mono">{scanResult.triage}</p>
              </div>
              <div>
                <p className="text-xs text-dim">Model</p>
                <p className="text-xs font-mono">{scanResult.model_used}</p>
              </div>
            </div>

            <div style={{ background: 'var(--bg-primary)', borderRadius: 8, padding: 12 }}>
              <p className="text-xs text-dim" style={{ fontStyle: 'italic' }}>
                ⚕️ This report is AI-generated and must be reviewed by a qualified ophthalmologist.
              </p>
            </div>
          </div>

          <p className="text-xs text-dim mt-16">
            Full report includes: patient info, diagnosis, severity analysis, class probabilities,
            Grad-CAM heatmap, triage recommendation, and medical disclaimer.
          </p>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="glass-card" style={{ cursor: 'pointer' }} onClick={handleGeneratePDF}>
            <div className="flex items-center gap-16">
              <div style={{ width: 56, height: 56, borderRadius: 16, background: 'var(--cyan-dim)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Download size={28} style={{ color: 'var(--cyan)' }} />
              </div>
              <div>
                <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 4 }}>Download PDF Report</h3>
                <p className="text-sm text-dim">Two-page clinical report saved to your device</p>
              </div>
            </div>
          </div>

          <div className="glass-card" style={{ cursor: 'pointer' }} onClick={shareWhatsApp}>
            <div className="flex items-center gap-16">
              <div style={{ width: 56, height: 56, borderRadius: 16, background: 'var(--green-dim)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Share2 size={28} style={{ color: 'var(--green)' }} />
              </div>
              <div>
                <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 4 }}>Share via WhatsApp</h3>
                <p className="text-sm text-dim">Send diagnosis summary with pre-filled message</p>
              </div>
            </div>
          </div>

          <div className="glass-card">
            <h3 style={{ fontSize: 14, fontWeight: 700, marginBottom: 12, color: 'var(--text-secondary)' }}>REPORT CONTENTS</h3>
            <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[
                'Patient demographics',
                'AI diagnosis & severity grading',
                'Confidence & uncertainty metrics',
                'Class probability breakdown',
                'Grad-CAM activation heatmap',
                'Auto-triage recommendation',
                'Image quality metadata',
                'Medical disclaimer',
              ].map((item, i) => (
                <li key={i} className="flex items-center gap-8 text-sm">
                  <span style={{ color: 'var(--cyan)' }}>✓</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
